// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC00Lt2TxVmxh77RFTj3ewc0FUc8vxEdo',
    appId: '1:316305474905:web:0f297f4f81a039660c7848',
    messagingSenderId: '316305474905',
    projectId: 'cps-com-c90aa',
    authDomain: 'cps-com-c90aa.firebaseapp.com',
    storageBucket: 'cps-com-c90aa.appspot.com',
    measurementId: 'G-B28FGGZ5ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5nrJfZuiJtwLXQLGs5CkRdWuF4SZ8yZE',
    appId: '1:316305474905:android:89e4ff2f0f0110710c7848',
    messagingSenderId: '316305474905',
    projectId: 'cps-com-c90aa',
    storageBucket: 'cps-com-c90aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD5PV9skScSwOt4XpQfwSNQ-0aDnvnjvM',
    appId: '1:316305474905:ios:0f40cf123b5ffb730c7848',
    messagingSenderId: '316305474905',
    projectId: 'cps-com-c90aa',
    storageBucket: 'cps-com-c90aa.appspot.com',
    iosClientId: '316305474905-d9bq9t5mumiqlbcvfig84kentoobk5od.apps.googleusercontent.com',
    iosBundleId: 'com.app.cpscomAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD5PV9skScSwOt4XpQfwSNQ-0aDnvnjvM',
    appId: '1:316305474905:ios:0f40cf123b5ffb730c7848',
    messagingSenderId: '316305474905',
    projectId: 'cps-com-c90aa',
    storageBucket: 'cps-com-c90aa.appspot.com',
    iosClientId: '316305474905-d9bq9t5mumiqlbcvfig84kentoobk5od.apps.googleusercontent.com',
    iosBundleId: 'com.app.cpscomAdmin',
  );
}
